### ISSUE TITLE
A CappedRateSampler is needed

### ISSUE THREAD

**Issue by prydin** [wavefrontHQ/wavefront-opentracing-sdk-go#24]
It would be great to have a variation of the RateSampler that's capped at a specific number of samples per minute. For example, I'd like to specify that I'd like at the most 100 samples per minute. The sampler would then adaptively calculate a rate that gives approximately that number of samples per minute and block any additional samples from being sent during that time period. 

I have code for this that I could put in a PR if you're interested.

**Comment by vikramraman** [comment]
@prydin Sure a PR would be welcome. We started on a similar thing for the Java side with a MaxThroughputSampler: https://github.com/wavefrontHQ/wavefront-sdk-java/pull/87/files

Let's keep the names consistent between the SDKs.

**Comment by vikramraman** [comment]
Closing for now. Can reopen if needed.
